; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "SimpleImage"
!define PRODUCT_VERSION "1.0"
!define PRODUCT_PUBLISHER "lerogo"
!define PRODUCT_WEB_SITE "https://www.lerogo.top/"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\AppMainExe.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "SimpleImage.svg"
!define MUI_UNICON "SimpleImage.svg"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!define MUI_LICENSEPAGE_RADIOBUTTONS
!insertmacro MUI_PAGE_LICENSE "C:\Users\lerogo\Desktop\Licence.txt"
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN "$INSTDIR\SimpleImage.exe"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "SimpChinese"

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "SimpleImage_setup.exe"
InstallDir "$PROGRAMFILES\SimpleImage"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File "c:\path\to\file\AppMainExe.exe"
  CreateDirectory "$SMPROGRAMS\SimpleImage"
  CreateShortCut "$SMPROGRAMS\SimpleImage\SimpleImage.lnk" "$INSTDIR\AppMainExe.exe"
  CreateShortCut "$DESKTOP\SimpleImage.lnk" "$INSTDIR\AppMainExe.exe"
  File "c:\path\to\file\Example.file"
  SetOverwrite try
  File "..\..\demo\D3Dcompiler_47.dll"
  SetOutPath "$INSTDIR\iconengines"
  File "..\..\demo\iconengines\qsvgicon.dll"
  SetOutPath "$INSTDIR\imageformats"
  File "..\..\demo\imageformats\qgif.dll"
  File "..\..\demo\imageformats\qicns.dll"
  File "..\..\demo\imageformats\qico.dll"
  File "..\..\demo\imageformats\qjpeg.dll"
  File "..\..\demo\imageformats\qsvg.dll"
  File "..\..\demo\imageformats\qtga.dll"
  File "..\..\demo\imageformats\qtiff.dll"
  File "..\..\demo\imageformats\qwbmp.dll"
  File "..\..\demo\imageformats\qwebp.dll"
  SetOutPath "$INSTDIR"
  File "..\..\demo\libEGL.dll"
  File "..\..\demo\libgcc_s_dw2-1.dll"
  File "..\..\demo\libGLESV2.dll"
  File "..\..\demo\libstdc++-6.dll"
  File "..\..\demo\libwinpthread-1.dll"
  File "..\..\demo\opengl32sw.dll"
  SetOutPath "$INSTDIR\platforms"
  File "..\..\demo\platforms\qwindows.dll"
  SetOutPath "$INSTDIR"
  File "..\..\demo\Qt5Concurrent.dll"
  File "..\..\demo\Qt5Core.dll"
  File "..\..\demo\Qt5Gui.dll"
  File "..\..\demo\Qt5Svg.dll"
  File "..\..\demo\Qt5Widgets.dll"
  File "..\..\demo\SimpleImage.exe"
  SetOutPath "$INSTDIR\styles"
  File "..\..\demo\styles\qwindowsvistastyle.dll"
  SetOutPath "$INSTDIR\translations"
  File "..\..\demo\translations\qt_ar.qm"
  File "..\..\demo\translations\qt_bg.qm"
  File "..\..\demo\translations\qt_ca.qm"
  File "..\..\demo\translations\qt_cs.qm"
  File "..\..\demo\translations\qt_da.qm"
  File "..\..\demo\translations\qt_de.qm"
  File "..\..\demo\translations\qt_en.qm"
  File "..\..\demo\translations\qt_es.qm"
  File "..\..\demo\translations\qt_fi.qm"
  File "..\..\demo\translations\qt_fr.qm"
  File "..\..\demo\translations\qt_gd.qm"
  File "..\..\demo\translations\qt_he.qm"
  File "..\..\demo\translations\qt_hu.qm"
  File "..\..\demo\translations\qt_it.qm"
  File "..\..\demo\translations\qt_ja.qm"
  File "..\..\demo\translations\qt_ko.qm"
  File "..\..\demo\translations\qt_lv.qm"
  File "..\..\demo\translations\qt_pl.qm"
  File "..\..\demo\translations\qt_ru.qm"
  File "..\..\demo\translations\qt_sk.qm"
  File "..\..\demo\translations\qt_uk.qm"
  File "..\..\demo\translations\qt_zh_TW.qm"
SectionEnd

Section -AdditionalIcons
  SetOutPath $INSTDIR
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\SimpleImage\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\SimpleImage\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\AppMainExe.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\AppMainExe.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) 已成功地从你的计算机移除。"
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "你确实要完全移除 $(^Name) ，其及所有的组件？" IDYES +2
  Abort
FunctionEnd

Section Uninstall
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  Delete "$INSTDIR\translations\qt_zh_TW.qm"
  Delete "$INSTDIR\translations\qt_uk.qm"
  Delete "$INSTDIR\translations\qt_sk.qm"
  Delete "$INSTDIR\translations\qt_ru.qm"
  Delete "$INSTDIR\translations\qt_pl.qm"
  Delete "$INSTDIR\translations\qt_lv.qm"
  Delete "$INSTDIR\translations\qt_ko.qm"
  Delete "$INSTDIR\translations\qt_ja.qm"
  Delete "$INSTDIR\translations\qt_it.qm"
  Delete "$INSTDIR\translations\qt_hu.qm"
  Delete "$INSTDIR\translations\qt_he.qm"
  Delete "$INSTDIR\translations\qt_gd.qm"
  Delete "$INSTDIR\translations\qt_fr.qm"
  Delete "$INSTDIR\translations\qt_fi.qm"
  Delete "$INSTDIR\translations\qt_es.qm"
  Delete "$INSTDIR\translations\qt_en.qm"
  Delete "$INSTDIR\translations\qt_de.qm"
  Delete "$INSTDIR\translations\qt_da.qm"
  Delete "$INSTDIR\translations\qt_cs.qm"
  Delete "$INSTDIR\translations\qt_ca.qm"
  Delete "$INSTDIR\translations\qt_bg.qm"
  Delete "$INSTDIR\translations\qt_ar.qm"
  Delete "$INSTDIR\styles\qwindowsvistastyle.dll"
  Delete "$INSTDIR\SimpleImage.exe"
  Delete "$INSTDIR\Qt5Widgets.dll"
  Delete "$INSTDIR\Qt5Svg.dll"
  Delete "$INSTDIR\Qt5Gui.dll"
  Delete "$INSTDIR\Qt5Core.dll"
  Delete "$INSTDIR\Qt5Concurrent.dll"
  Delete "$INSTDIR\platforms\qwindows.dll"
  Delete "$INSTDIR\opengl32sw.dll"
  Delete "$INSTDIR\libwinpthread-1.dll"
  Delete "$INSTDIR\libstdc++-6.dll"
  Delete "$INSTDIR\libGLESV2.dll"
  Delete "$INSTDIR\libgcc_s_dw2-1.dll"
  Delete "$INSTDIR\libEGL.dll"
  Delete "$INSTDIR\imageformats\qwebp.dll"
  Delete "$INSTDIR\imageformats\qwbmp.dll"
  Delete "$INSTDIR\imageformats\qtiff.dll"
  Delete "$INSTDIR\imageformats\qtga.dll"
  Delete "$INSTDIR\imageformats\qsvg.dll"
  Delete "$INSTDIR\imageformats\qjpeg.dll"
  Delete "$INSTDIR\imageformats\qico.dll"
  Delete "$INSTDIR\imageformats\qicns.dll"
  Delete "$INSTDIR\imageformats\qgif.dll"
  Delete "$INSTDIR\iconengines\qsvgicon.dll"
  Delete "$INSTDIR\D3Dcompiler_47.dll"
  Delete "$INSTDIR\Example.file"
  Delete "$INSTDIR\AppMainExe.exe"

  Delete "$SMPROGRAMS\SimpleImage\Uninstall.lnk"
  Delete "$SMPROGRAMS\SimpleImage\Website.lnk"
  Delete "$DESKTOP\SimpleImage.lnk"
  Delete "$SMPROGRAMS\SimpleImage\SimpleImage.lnk"

  RMDir "$SMPROGRAMS\SimpleImage"
  RMDir "$INSTDIR\translations"
  RMDir "$INSTDIR\styles"
  RMDir "$INSTDIR\platforms"
  RMDir "$INSTDIR\imageformats"
  RMDir "$INSTDIR\iconengines"
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  SetAutoClose true
SectionEnd